#include "p18f4520.inc"

CONFIG  OSC = INTIO67
CONFIG  FCMEN = OFF
CONFIG  IESO = OFF
CONFIG  PWRT = OFF
CONFIG  BOREN = SBORDIS
CONFIG  BORV = 3
CONFIG  WDT = OFF
CONFIG  WDTPS = 32768
CONFIG  CCP2MX = PORTC
CONFIG  PBADEN = ON
CONFIG  LPT1OSC = OFF
CONFIG  MCLRE = ON
CONFIG  STVREN = ON
CONFIG  LVP = OFF
CONFIG  XINST = OFF
CONFIG  CP0 = OFF
CONFIG  CP1 = OFF
CONFIG  CP2 = OFF
CONFIG  CP3 = OFF
CONFIG  CPB = OFF
CONFIG  CPD = OFF
CONFIG  WRT0 = OFF
CONFIG  WRT1 = OFF
CONFIG  WRT2 = OFF
CONFIG  WRT3 = OFF
CONFIG  WRTC = OFF
CONFIG  WRTB = OFF
CONFIG  WRTD = OFF
CONFIG  EBTR0 = OFF
CONFIG  EBTR1 = OFF
CONFIG  EBTR2 = OFF
CONFIG  EBTR3 = OFF
CONFIG  EBTRB = OFF

    org 0x00
    goto Initial

ISR_HIGH:
    org 0x08
    BTFSC INTCON, INT0IF
    goto INT0_ISR
    BTFSC PIR1, TMR2IF
    goto TMR2_ISR
    RETFIE

INT0_ISR:
    MOVLW 0x01
    XORWF 0x20, f
    BTFSC 0x20, 0
    goto set_state2
    goto set_state1
    
set_state1:
    CLRF LATD
    MOVLW d'61'
    MOVWF PR2
    BCF INTCON, INT0IF
    RETFIE
    
set_state2:
    MOVLW 0x10
    MOVWF LATD
    MOVLW d'244'
    MOVWF PR2
    BCF INTCON, INT0IF
    RETFIE

TMR2_ISR:
    BTFSC 0x20, 0
    goto update_state2
    goto update_state1
    
update_state1:
    MOVLW 0x20
    ADDWF LATD, f
    MOVLW 0xF0
    ANDWF LATD, f
    BCF PIR1, TMR2IF
    RETFIE
    
update_state2:
    MOVLW 0x20
    ADDWF LATD, f
    MOVLW 0xF0
    ANDWF LATD, f
    BCF PIR1, TMR2IF
    RETFIE

Initial:
    MOVLW 0x0F
    MOVWF ADCON1
    CLRF TRISD
    CLRF LATD
    BSF TRISB, 0
    
    BSF RCON, IPEN
    BSF INTCON, GIE
    BSF INTCON, INT0IE
    BCF INTCON, INT0IF
    BSF INTCON2, INTEDG0
    
    BCF PIR1, TMR2IF
    BSF IPR1, TMR2IP
    BSF PIE1, TMR2IE
    MOVLW b'11111111'
    MOVWF T2CON
    MOVLW d'61'
    MOVWF PR2
    MOVLW b'00100000'
    MOVWF OSCCON
    
    CLRF 0x20
    
main:
    bra main
    
end